package:
  name: netcat-openbsd
  version: 1.219
  epoch: 0
  description: The TCP/IP swiss army knife. OpenBSD variant from debian.
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-3-Clause
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - patch
      - libbsd-dev
      - libmd-dev
pipeline:
  - uses: fetch
    with:
      uri: https://deb.debian.org/debian/pool/main/n/netcat-openbsd/netcat-openbsd_${{package.version}}.orig.tar.gz
      expected-sha512: 9f6d531d33410457b8f1e6a3eb0d105dbd819d5e4fe9753d32d7fd4583680ceba102a60307a8b5ef26b47047492b207388742b725da3708d30d360d4a196f115
  - uses: fetch
    with:
      uri: http://deb.debian.org/debian/pool/main/n/netcat-openbsd/netcat-openbsd_${{package.version}}-1.debian.tar.xz
      expected-sha512: badc1afbe8a467c068fa1d3bf12817d568eae5bb9774f9f11d3b30c065eb3a8b39724bb456329d7153ea3160cd10fab159a6756f7eeafd9bfc8c5d78114f7da6
      extract: false
  - runs: |
      mkdir -p debian
      tar -x '--strip-components=1' -f "netcat-openbsd_${{package.version}}-1.debian.tar.xz" -C debian
      while read -r patch; do
        patch -Np1 < ./debian/patches/"$patch"
      done < ./debian/patches/series

      # linux port requires b64_ntop. include in in SRCS (Makefile)
      # we also want this to link with libmd as well because it uses sha512update...
      sed -i Makefile -e "/SRCS=/s;\(.*\);& base64.c;"
      sed -i Makefile -e "s/\libbsd\b/& libmd/"
  - runs: |
      make CFLAGS="$CFLAGS -DDEBIAN_VERSION=\"\\\"${{package.version}}\\\"\""
  - runs: |
      install -Dm755 nc "${{targets.destdir}}"/usr/bin/nc
      install -Dm644 nc.1 "${{targets.destdir}}"/usr/share/man/man1/nc.openbsd.1
  - uses: strip
